In [9]:
Graph("O}ambWqYOqAdrCAz?VGc\\").is_connected()

<>:1: DeprecationWarning: invalid escape sequence \}
<>:1: DeprecationWarning: invalid escape sequence \}
<ipython-input-9-2698fb1312d9>:1: DeprecationWarning: invalid escape sequence \}
  Graph("_JCPIKgQJ_PF`qb?OIKDBV~k~}w~~f^}F~vBf~k~^mw\}|`~M{L|N{q~\maflvqP|]|HNz\yG~}ZuEFu^heC").is_connected()


True

In [47]:
with open("examples_with_32_vertices.txt", "r") as file:
    for line in file:
        if len(line)>1:
            print(Graph(line).is_regular())

False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False


In [46]:
with open("examples_with_64_vertices_short.txt", "r") as file:
    for line in file:
        if len(line)>1:
            print(Graph(line).is_regular())

False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False


In [17]:
import numpy as np
M = np.zeros((4, 4))

In [18]:
M

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
for i in range(4):
    M[i, i] = 1
    if i+1 < 4:
        M[i, i+1] = 1

In [20]:
M

array([[1., 1., 0., 0.],
       [0., 1., 1., 0.],
       [0., 0., 1., 1.],
       [0., 0., 0., 1.]])

In [45]:
M2 = M
for i in range(6):
    M2 = M2@M
    for r in range(4):
        for c in range(4):
            M2[r,c] = M2[r,c]%2
    print(M2)

[[1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 1. 1. 1.]
 [0. 1. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 1. 0. 0.]
 [0. 1. 1. 0.]
 [0. 0. 1. 1.]
 [0. 0. 0. 1.]]
[[1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 1. 1. 1.]
 [0. 1. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 0. 1.]]


In [44]:
M2

array([[1., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 0., 1.]])